version: "3"
services:
  memcached:
    hostname: ${APP_NAME}-memcached
    image: memcached:1.6-alpine
    ports:
      - "11211:11211"
    restart: always
  mysql:
    image: mysql:5.7
    hostname: ${APP_NAME}-mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    restart: always
  redis:
    hostname: ${APP_NAME}-redis
    image: redis:5.0-alpine
    ports:
      - "6379:6379"
    restart: always
